word_list = [
    "python",
    "java",
    "javascript",
    "csharp",
    "hangman",
    "developer",
    "programming",
    "software",
    "engineer",
    "database",
    "frontend",
    "backend",
    "devops",
    "cloud",
    "microservices",
    "agile",
    "scrum",
    "testing",
    "deployment",
    "version control",
    "repository",
    "collaboration",
    "documentation",
    "debugging",
    "refactoring",
    "performance",
    "scalability",
    "security",
    "architecture",
    "design patterns",
    "code review",
    "pair programming",
    "continuous integration",
    "continuous delivery",
    "agile methodology",
    "scrum framework",
    "kanban board",
    "lean",
    "xp",
    "feature-driven development",
    "test-driven development",

]